# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\x12\x06server\"t\n\nDataPacket\x12\x18\n\x10packet_timestamp\x18\x01 \x01(\x03\x12\x16\n\x0epacket_seq_num\x18\x02 \x01(\x05\x12\x11\n\tn_records\x18\x03 \x01(\x05\x12!\n\x0bpacket_data\x18\x04 \x03(\x0b\x32\x0c.server.Data\"a\n\x04\x44\x61ta\x12\x10\n\x08\x64\x65\x63imal1\x18\x01 \x01(\x01\x12\x10\n\x08\x64\x65\x63imal2\x18\x02 \x01(\x01\x12\x10\n\x08\x64\x65\x63imal3\x18\x03 \x01(\x01\x12\x10\n\x08\x64\x65\x63imal4\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2A\n\x0b\x44\x61taService\x12\x32\n\x08SendData\x12\x12.server.DataPacket\x1a\x10.server.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAPACKET']._serialized_start=30
  _globals['_DATAPACKET']._serialized_end=146
  _globals['_DATA']._serialized_start=148
  _globals['_DATA']._serialized_end=245
  _globals['_RESPONSE']._serialized_start=247
  _globals['_RESPONSE']._serialized_end=291
  _globals['_DATASERVICE']._serialized_start=293
  _globals['_DATASERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
